- name: install python apt packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - python3-venv
    - libmysqlclient-dev

- name: make venv
  command: python3 -m venv /home/vagrant/env
  changed_when: False

- name: pip install packages
  pip: name={{ item }} state=present virtualenv=/home/vagrant/env virtualenv_python=python3.5
  with_items:
    - numpy
    - scipy
    - scikit-learn
    - bottle
    - pyMySQL3
    - mysqlclient
    - simplejson

